---
apiVersion: v1
kind: Service
metadata:
  name: az-fn-service
  labels:
    name: az-fn-service
    app: demo-az-fn-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30025
  selector:
    name: az-fn-app-pod
    app: demo-az-fn-app
