---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: az-fn-app-deploy
  labels:
    name: az-fn-app-deploy
    app: demo-az-fn-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: az-fn-app-pod
      app: demo-az-fn-app
  template:
    metadata:
      name: az-fn-app-pod
      labels:
        name: az-fn-app-pod
        app: demo-az-fn-app
    spec:
      containers:
      - name: az-fn-app
        image: satishs05/az-function-on-container
        ports:
        - containerPort: 80

